apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: app
      image: localhost:5000/my-php-app
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-pod
#   namespace: default
# spec:
#   selector:
#     app: my-pod
#   type: LoadBalancer
#   ports:
#   - name: http
#     targetPort: 3000
#     port: 80