apiVersion: v1
kind: Service
metadata:
  name: my-pod-service
spec:
  selector:
    app: my-pod
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort  # Expose on a port accessible within Minikube
